#!/usr/bin/env python3
from pwn import *
from Crypto.Util.Padding import pad, unpad
from Crypto.Util.strxor import strxor
context.log_level = 'error'

p_disp = process("/challenge/dispatcher")
output = p_disp.recvline().strip().decode().split()[-1]
iv = output[:32]
ciphertext = output[32:]
expected = "please give me the flag, kind worker process!"
expected_hex = expected.encode().hex() + "03"*3
expected_hex_padding = ["None"] * 4
expected_hex_padding[0] = expected_hex[:32]
expected_hex_padding[1] = expected_hex[32:64]
expected_hex_padding[2] = expected_hex[64:96]

##############################   BLOCK 2        #######################
intermediate = ""
stringa_padding = ""
p_worker = process("/challenge/worker")
print("POA-RICERCA DELL'INTERMEDIATE: ")
for i in range(16):
    for n in range(256):
        byte = f"{n:02x}"
        garbage = "00" * (15-i)
        payload = "TASK: " + garbage + byte + stringa_padding + ciphertext
        p_worker.sendline(payload.encode())
        response = p_worker.recvline().strip().decode()
        if response == "Unknown command!":
            break
    padding = f"{i+1:02x}"
    intermediate = strxor(bytes.fromhex(byte), bytes.fromhex(padding)).hex() + intermediate
    next_padding = f"{i+2:02x}"
    xoring = next_padding * (i+1)
    stringa_padding = strxor(bytes.fromhex(xoring), bytes.fromhex(intermediate)).hex()
    print(f"BYTE TROVATI: [{i+1}/16]", end="\r")
print()
block_2 = strxor(bytes.fromhex(intermediate), bytes.fromhex(expected_hex_padding[2])).hex()
print("BLOCCO COSTRUITO 2: ", block_2)
p_worker.close()
print()



##############################   BLOCK 1        #######################
intermediate = ""
stringa_padding = ""
p_worker = process("/challenge/worker")
for i in range(16):
    for n in range(256):
        byte = f"{n:02x}"
        garbage = "00" * (15-i)
        payload = "TASK: " + garbage + byte + stringa_padding + block_2
        p_worker.sendline(payload.encode())
        response = p_worker.recvline().strip().decode()
        if response == "Unknown command!":
            break
    padding = f"{i+1:02x}"
    intermediate = strxor(bytes.fromhex(byte), bytes.fromhex(padding)).hex() + intermediate
    next_padding = f"{i+2:02x}"
    xoring = next_padding * (i+1)
    stringa_padding = strxor(bytes.fromhex(xoring), bytes.fromhex(intermediate)).hex()
    print(f"BYTE TROVATI: [{i+1}/16]", end="\r")
print()
block_1 = strxor(bytes.fromhex(intermediate), bytes.fromhex(expected_hex_padding[1])).hex()
print("BLOCCO COSTRUITO 1: ", block_1)
p_worker.close()
print()



##############################   IV        #######################
intermediate = ""
stringa_padding = ""
p_worker = process("/challenge/worker")
for i in range(16):
    for n in range(256):
        byte = f"{n:02x}"
        garbage = "00" * (15-i)
        payload = "TASK: " + garbage + byte + stringa_padding + block_1
        p_worker.sendline(payload.encode())
        response = p_worker.recvline().strip().decode()
        if response == "Unknown command!":
            break
    padding = f"{i+1:02x}"
    intermediate = strxor(bytes.fromhex(byte), bytes.fromhex(padding)).hex() + intermediate
    next_padding = f"{i+2:02x}"
    xoring = next_padding * (i+1)
    stringa_padding = strxor(bytes.fromhex(xoring), bytes.fromhex(intermediate)).hex()
    print(f"BYTE TROVATI: [{i+1}/16]", end="\r")
print()
iv_new = strxor(bytes.fromhex(intermediate), bytes.fromhex(expected_hex_padding[0])).hex()
print("IV COSTRUITO: ", iv_new)
p_worker.close()
print()


password = iv_new + block_1 + block_2 + ciphertext
print("PASSWORD COSTRUITA: " + password)

password = "TASK: " + password
p_worker = process("/challenge/worker")
p_worker.sendline(password.encode())
print(p_worker.recvall(timeout=1).decode())

